services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn grove_street.wsgi:application --bind 0.0.0.0:8000
    working_dir: /home/app/web/grove_street/
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web
    links:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: