# Generated by Django 5.1.3 on 2024-11-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="experienceitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("title", ""), _negated=True),
                name="experience_item_title_populated",
            ),
        ),
        migrations.AddConstraint(
            model_name="experienceitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("role", ""), _negated=True),
                name="experience_item_role_populated",
            ),
        ),
        migrations.AddConstraint(
            model_name="experienceitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("description", ""), _negated=True),
                name="experience_item_description_populated",
            ),
        ),
        migrations.AddConstraint(
            model_name="experienceitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("category", ""), _negated=True),
                name="experience_item_category_populated",
            ),
        ),
    ]
