# Generated by Django 5.1.3 on 2024-12-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_experienceitem_experience_item_title_populated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('experience_months', models.IntegerField(verbose_name='Experience months')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='expertise_item_title_populated'), models.CheckConstraint(condition=models.Q(('category', ''), _negated=True), name='expertise_item_category_populated'), models.CheckConstraint(condition=models.Q(('experience_months__gt', 0)), name='expertise_item_has_non_zero_experience')],
            },
        ),
    ]
