# Generated by Django 5.0.4 on 2024-04-23 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_blogpost_title_blogpost_title_populated"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="blogpost",
            constraint=models.CheckConstraint(
                check=models.Q(("content", ""), _negated=True), name="content_populated"
            ),
        ),
    ]
