# Generated by Django 5.0.4 on 2024-05-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_blogpost_title_blogpost_content_populated"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="edited_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Edited date"
            ),
        ),
    ]
