# Generated by Django 5.0.4 on 2024-05-27 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_blogpost_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(verbose_name="Created date")),
                (
                    "edited_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Edited date"
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="blogpost",
            name="title_populated",
        ),
        migrations.RemoveConstraint(
            model_name="blogpost",
            name="content_populated",
        ),
        migrations.AddConstraint(
            model_name="blogpost",
            constraint=models.CheckConstraint(
                check=models.Q(("title", ""), _negated=True),
                name="blog_post_title_populated",
            ),
        ),
        migrations.AddConstraint(
            model_name="blogpost",
            constraint=models.CheckConstraint(
                check=models.Q(("content", ""), _negated=True),
                name="blog_post_content_populated",
            ),
        ),
        migrations.AddField(
            model_name="blogpostcomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="blogpostcomment",
            name="blog_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.blogpost"
            ),
        ),
        migrations.AddConstraint(
            model_name="blogpostcomment",
            constraint=models.CheckConstraint(
                check=models.Q(("content", ""), _negated=True),
                name="blog_post_comment_content_populated",
            ),
        ),
    ]
